services:
  - type: web
    name: port-folio
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install --omit=dev
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
